export ARCH_INSTALL_CONFIGURATION=configure.sh
export ARCH_INSTALL_SSID='SSID'
export ARCH_INSTALL_PASSPHRASE='PASSPHRASE'
export ARCH_INSTALL_IDENTITY_FILE='IDENTITY_FILE'
export ARCH_INSTALL_USB_DEVICE='USB_DEVICE'

