export ARCH_INSTALL_CONFIGURATION=configure.sh
export ARCH_INSTALL_SSID='SSID'
export ARCH_INSTALL_PASSPHRASE='PASSPHRASE'
export ARCH_INSTALL_SSH_PUBLIC_KEY='SSH_PUBLIC_KEY'
export ARCH_INSTALL_USB_DEVICE='USB_DEVICE'

