#!/bin/fish

set -gx ARCH_INSTALL_CONFIGURATION (basename (status -f))
set -gx ARCH_INSTALL_SSID 'SSID'
set -gx ARCH_INSTALL_PASSPHRASE 'PASSPHRASE'
set -gx ARCH_INSTALL_SSH_PUBLIC_KEY 'SSH_PUBLIC_KEY'
set -gx ARCH_INSTALL_USB_DEVICE 'USB_DEVICE'

